name: rllb
channels: 
  - conda-forge
  - defaults
dependencies:
    - numpy==1.19.5
    - python=3.8.5
    - psutil
    - tensorflow=2.4.1
    - pip=21.1.3
    - pip:
      - ray==1.5.2
      - "ray[rllib]"
      - torch==1.9.0
      